/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientsIndexRouteImport } from './routes/_app.clients.index'
import { Route as AppSalesOpportunitiesRouteImport } from './routes/_app.sales.opportunities'
import { Route as AppSalesLeadsRouteImport } from './routes/_app.sales.leads'
import { Route as AppSalesConversationsRouteImport } from './routes/_app.sales.conversations'
import { Route as AppProvisioningTemplatesRouteImport } from './routes/_app.provisioning.templates'
import { Route as AppProvisioningSecretsRouteImport } from './routes/_app.provisioning.secrets'
import { Route as AppProvisioningQueueRouteImport } from './routes/_app.provisioning.queue'
import { Route as AppProvisioningDomainsRouteImport } from './routes/_app.provisioning.domains'
import { Route as AppOperationsTeamRouteImport } from './routes/_app.operations.team'
import { Route as AppOperationsTasksRouteImport } from './routes/_app.operations.tasks'
import { Route as AppOperationsHealthRouteImport } from './routes/_app.operations.health'
import { Route as AppOperationsDeploymentsRouteImport } from './routes/_app.operations.deployments'
import { Route as AppClientsProjectsRouteImport } from './routes/_app.clients.projects'
import { Route as AppClientsDeliverablesRouteImport } from './routes/_app.clients.deliverables'
import { Route as AppClientsClientIdRouteImport } from './routes/_app.clients.$clientId'
import { Route as AppAutomationWorkflowsRouteImport } from './routes/_app.automation.workflows'
import { Route as AppAutomationKnowledgeRouteImport } from './routes/_app.automation.knowledge'
import { Route as AppAutomationIntegrationsRouteImport } from './routes/_app.automation.integrations'
import { Route as AppAutomationAgentsRouteImport } from './routes/_app.automation.agents'
import { Route as AppAnalyticsUsageRouteImport } from './routes/_app.analytics.usage'
import { Route as AppAnalyticsRevenueRouteImport } from './routes/_app.analytics.revenue'
import { Route as AppAnalyticsPerformanceRouteImport } from './routes/_app.analytics.performance'
import { Route as AppAdminTeamRouteImport } from './routes/_app.admin.team'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminBillingRouteImport } from './routes/_app.admin.billing'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppSalesOpportunitiesOpportunityIdRouteImport } from './routes/_app.sales.opportunities.$opportunityId'
import { Route as AppSalesLeadsLeadIdRouteImport } from './routes/_app.sales.leads.$leadId'
import { Route as AppSalesClientsSalesClientIdRouteImport } from './routes/_app.sales.clients.$salesClientId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOpportunitiesRoute = AppSalesOpportunitiesRouteImport.update({
  id: '/sales/opportunities',
  path: '/sales/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesLeadsRoute = AppSalesLeadsRouteImport.update({
  id: '/sales/leads',
  path: '/sales/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesConversationsRoute = AppSalesConversationsRouteImport.update({
  id: '/sales/conversations',
  path: '/sales/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppProvisioningTemplatesRoute =
  AppProvisioningTemplatesRouteImport.update({
    id: '/provisioning/templates',
    path: '/provisioning/templates',
    getParentRoute: () => AppRoute,
  } as any)
const AppProvisioningSecretsRoute = AppProvisioningSecretsRouteImport.update({
  id: '/provisioning/secrets',
  path: '/provisioning/secrets',
  getParentRoute: () => AppRoute,
} as any)
const AppProvisioningQueueRoute = AppProvisioningQueueRouteImport.update({
  id: '/provisioning/queue',
  path: '/provisioning/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppProvisioningDomainsRoute = AppProvisioningDomainsRouteImport.update({
  id: '/provisioning/domains',
  path: '/provisioning/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsTeamRoute = AppOperationsTeamRouteImport.update({
  id: '/operations/team',
  path: '/operations/team',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsTasksRoute = AppOperationsTasksRouteImport.update({
  id: '/operations/tasks',
  path: '/operations/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsHealthRoute = AppOperationsHealthRouteImport.update({
  id: '/operations/health',
  path: '/operations/health',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsDeploymentsRoute =
  AppOperationsDeploymentsRouteImport.update({
    id: '/operations/deployments',
    path: '/operations/deployments',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientsProjectsRoute = AppClientsProjectsRouteImport.update({
  id: '/clients/projects',
  path: '/clients/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsDeliverablesRoute = AppClientsDeliverablesRouteImport.update({
  id: '/clients/deliverables',
  path: '/clients/deliverables',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationWorkflowsRoute = AppAutomationWorkflowsRouteImport.update({
  id: '/automation/workflows',
  path: '/automation/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationKnowledgeRoute = AppAutomationKnowledgeRouteImport.update({
  id: '/automation/knowledge',
  path: '/automation/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationIntegrationsRoute =
  AppAutomationIntegrationsRouteImport.update({
    id: '/automation/integrations',
    path: '/automation/integrations',
    getParentRoute: () => AppRoute,
  } as any)
const AppAutomationAgentsRoute = AppAutomationAgentsRouteImport.update({
  id: '/automation/agents',
  path: '/automation/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsUsageRoute = AppAnalyticsUsageRouteImport.update({
  id: '/analytics/usage',
  path: '/analytics/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRevenueRoute = AppAnalyticsRevenueRouteImport.update({
  id: '/analytics/revenue',
  path: '/analytics/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsPerformanceRoute = AppAnalyticsPerformanceRouteImport.update({
  id: '/analytics/performance',
  path: '/analytics/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTeamRoute = AppAdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBillingRoute = AppAdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOpportunitiesOpportunityIdRoute =
  AppSalesOpportunitiesOpportunityIdRouteImport.update({
    id: '/$opportunityId',
    path: '/$opportunityId',
    getParentRoute: () => AppSalesOpportunitiesRoute,
  } as any)
const AppSalesLeadsLeadIdRoute = AppSalesLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppSalesLeadsRoute,
} as any)
const AppSalesClientsSalesClientIdRoute =
  AppSalesClientsSalesClientIdRouteImport.update({
    id: '/sales/clients/$salesClientId',
    path: '/sales/clients/$salesClientId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/messages': typeof AppMessagesRoute
  '/tasks': typeof AppTasksRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/billing': typeof AppAdminBillingRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/team': typeof AppAdminTeamRoute
  '/analytics/performance': typeof AppAnalyticsPerformanceRoute
  '/analytics/revenue': typeof AppAnalyticsRevenueRoute
  '/analytics/usage': typeof AppAnalyticsUsageRoute
  '/automation/agents': typeof AppAutomationAgentsRoute
  '/automation/integrations': typeof AppAutomationIntegrationsRoute
  '/automation/knowledge': typeof AppAutomationKnowledgeRoute
  '/automation/workflows': typeof AppAutomationWorkflowsRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/deliverables': typeof AppClientsDeliverablesRoute
  '/clients/projects': typeof AppClientsProjectsRoute
  '/operations/deployments': typeof AppOperationsDeploymentsRoute
  '/operations/health': typeof AppOperationsHealthRoute
  '/operations/tasks': typeof AppOperationsTasksRoute
  '/operations/team': typeof AppOperationsTeamRoute
  '/provisioning/domains': typeof AppProvisioningDomainsRoute
  '/provisioning/queue': typeof AppProvisioningQueueRoute
  '/provisioning/secrets': typeof AppProvisioningSecretsRoute
  '/provisioning/templates': typeof AppProvisioningTemplatesRoute
  '/sales/conversations': typeof AppSalesConversationsRoute
  '/sales/leads': typeof AppSalesLeadsRouteWithChildren
  '/sales/opportunities': typeof AppSalesOpportunitiesRouteWithChildren
  '/clients/': typeof AppClientsIndexRoute
  '/sales/clients/$salesClientId': typeof AppSalesClientsSalesClientIdRoute
  '/sales/leads/$leadId': typeof AppSalesLeadsLeadIdRoute
  '/sales/opportunities/$opportunityId': typeof AppSalesOpportunitiesOpportunityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/messages': typeof AppMessagesRoute
  '/tasks': typeof AppTasksRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/billing': typeof AppAdminBillingRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/team': typeof AppAdminTeamRoute
  '/analytics/performance': typeof AppAnalyticsPerformanceRoute
  '/analytics/revenue': typeof AppAnalyticsRevenueRoute
  '/analytics/usage': typeof AppAnalyticsUsageRoute
  '/automation/agents': typeof AppAutomationAgentsRoute
  '/automation/integrations': typeof AppAutomationIntegrationsRoute
  '/automation/knowledge': typeof AppAutomationKnowledgeRoute
  '/automation/workflows': typeof AppAutomationWorkflowsRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/deliverables': typeof AppClientsDeliverablesRoute
  '/clients/projects': typeof AppClientsProjectsRoute
  '/operations/deployments': typeof AppOperationsDeploymentsRoute
  '/operations/health': typeof AppOperationsHealthRoute
  '/operations/tasks': typeof AppOperationsTasksRoute
  '/operations/team': typeof AppOperationsTeamRoute
  '/provisioning/domains': typeof AppProvisioningDomainsRoute
  '/provisioning/queue': typeof AppProvisioningQueueRoute
  '/provisioning/secrets': typeof AppProvisioningSecretsRoute
  '/provisioning/templates': typeof AppProvisioningTemplatesRoute
  '/sales/conversations': typeof AppSalesConversationsRoute
  '/sales/leads': typeof AppSalesLeadsRouteWithChildren
  '/sales/opportunities': typeof AppSalesOpportunitiesRouteWithChildren
  '/clients': typeof AppClientsIndexRoute
  '/sales/clients/$salesClientId': typeof AppSalesClientsSalesClientIdRoute
  '/sales/leads/$leadId': typeof AppSalesLeadsLeadIdRoute
  '/sales/opportunities/$opportunityId': typeof AppSalesOpportunitiesOpportunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/billing': typeof AppAdminBillingRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/team': typeof AppAdminTeamRoute
  '/_app/analytics/performance': typeof AppAnalyticsPerformanceRoute
  '/_app/analytics/revenue': typeof AppAnalyticsRevenueRoute
  '/_app/analytics/usage': typeof AppAnalyticsUsageRoute
  '/_app/automation/agents': typeof AppAutomationAgentsRoute
  '/_app/automation/integrations': typeof AppAutomationIntegrationsRoute
  '/_app/automation/knowledge': typeof AppAutomationKnowledgeRoute
  '/_app/automation/workflows': typeof AppAutomationWorkflowsRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/clients/deliverables': typeof AppClientsDeliverablesRoute
  '/_app/clients/projects': typeof AppClientsProjectsRoute
  '/_app/operations/deployments': typeof AppOperationsDeploymentsRoute
  '/_app/operations/health': typeof AppOperationsHealthRoute
  '/_app/operations/tasks': typeof AppOperationsTasksRoute
  '/_app/operations/team': typeof AppOperationsTeamRoute
  '/_app/provisioning/domains': typeof AppProvisioningDomainsRoute
  '/_app/provisioning/queue': typeof AppProvisioningQueueRoute
  '/_app/provisioning/secrets': typeof AppProvisioningSecretsRoute
  '/_app/provisioning/templates': typeof AppProvisioningTemplatesRoute
  '/_app/sales/conversations': typeof AppSalesConversationsRoute
  '/_app/sales/leads': typeof AppSalesLeadsRouteWithChildren
  '/_app/sales/opportunities': typeof AppSalesOpportunitiesRouteWithChildren
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/sales/clients/$salesClientId': typeof AppSalesClientsSalesClientIdRoute
  '/_app/sales/leads/$leadId': typeof AppSalesLeadsLeadIdRoute
  '/_app/sales/opportunities/$opportunityId': typeof AppSalesOpportunitiesOpportunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/dashboard'
    | '/documents'
    | '/messages'
    | '/tasks'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/settings'
    | '/admin/team'
    | '/analytics/performance'
    | '/analytics/revenue'
    | '/analytics/usage'
    | '/automation/agents'
    | '/automation/integrations'
    | '/automation/knowledge'
    | '/automation/workflows'
    | '/clients/$clientId'
    | '/clients/deliverables'
    | '/clients/projects'
    | '/operations/deployments'
    | '/operations/health'
    | '/operations/tasks'
    | '/operations/team'
    | '/provisioning/domains'
    | '/provisioning/queue'
    | '/provisioning/secrets'
    | '/provisioning/templates'
    | '/sales/conversations'
    | '/sales/leads'
    | '/sales/opportunities'
    | '/clients/'
    | '/sales/clients/$salesClientId'
    | '/sales/leads/$leadId'
    | '/sales/opportunities/$opportunityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/dashboard'
    | '/documents'
    | '/messages'
    | '/tasks'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/settings'
    | '/admin/team'
    | '/analytics/performance'
    | '/analytics/revenue'
    | '/analytics/usage'
    | '/automation/agents'
    | '/automation/integrations'
    | '/automation/knowledge'
    | '/automation/workflows'
    | '/clients/$clientId'
    | '/clients/deliverables'
    | '/clients/projects'
    | '/operations/deployments'
    | '/operations/health'
    | '/operations/tasks'
    | '/operations/team'
    | '/provisioning/domains'
    | '/provisioning/queue'
    | '/provisioning/secrets'
    | '/provisioning/templates'
    | '/sales/conversations'
    | '/sales/leads'
    | '/sales/opportunities'
    | '/clients'
    | '/sales/clients/$salesClientId'
    | '/sales/leads/$leadId'
    | '/sales/opportunities/$opportunityId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/messages'
    | '/_app/tasks'
    | '/_app/admin/audit'
    | '/_app/admin/billing'
    | '/_app/admin/settings'
    | '/_app/admin/team'
    | '/_app/analytics/performance'
    | '/_app/analytics/revenue'
    | '/_app/analytics/usage'
    | '/_app/automation/agents'
    | '/_app/automation/integrations'
    | '/_app/automation/knowledge'
    | '/_app/automation/workflows'
    | '/_app/clients/$clientId'
    | '/_app/clients/deliverables'
    | '/_app/clients/projects'
    | '/_app/operations/deployments'
    | '/_app/operations/health'
    | '/_app/operations/tasks'
    | '/_app/operations/team'
    | '/_app/provisioning/domains'
    | '/_app/provisioning/queue'
    | '/_app/provisioning/secrets'
    | '/_app/provisioning/templates'
    | '/_app/sales/conversations'
    | '/_app/sales/leads'
    | '/_app/sales/opportunities'
    | '/_app/clients/'
    | '/_app/sales/clients/$salesClientId'
    | '/_app/sales/leads/$leadId'
    | '/_app/sales/opportunities/$opportunityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/opportunities': {
      id: '/_app/sales/opportunities'
      path: '/sales/opportunities'
      fullPath: '/sales/opportunities'
      preLoaderRoute: typeof AppSalesOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/leads': {
      id: '/_app/sales/leads'
      path: '/sales/leads'
      fullPath: '/sales/leads'
      preLoaderRoute: typeof AppSalesLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/conversations': {
      id: '/_app/sales/conversations'
      path: '/sales/conversations'
      fullPath: '/sales/conversations'
      preLoaderRoute: typeof AppSalesConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provisioning/templates': {
      id: '/_app/provisioning/templates'
      path: '/provisioning/templates'
      fullPath: '/provisioning/templates'
      preLoaderRoute: typeof AppProvisioningTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provisioning/secrets': {
      id: '/_app/provisioning/secrets'
      path: '/provisioning/secrets'
      fullPath: '/provisioning/secrets'
      preLoaderRoute: typeof AppProvisioningSecretsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provisioning/queue': {
      id: '/_app/provisioning/queue'
      path: '/provisioning/queue'
      fullPath: '/provisioning/queue'
      preLoaderRoute: typeof AppProvisioningQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provisioning/domains': {
      id: '/_app/provisioning/domains'
      path: '/provisioning/domains'
      fullPath: '/provisioning/domains'
      preLoaderRoute: typeof AppProvisioningDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/team': {
      id: '/_app/operations/team'
      path: '/operations/team'
      fullPath: '/operations/team'
      preLoaderRoute: typeof AppOperationsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/tasks': {
      id: '/_app/operations/tasks'
      path: '/operations/tasks'
      fullPath: '/operations/tasks'
      preLoaderRoute: typeof AppOperationsTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/health': {
      id: '/_app/operations/health'
      path: '/operations/health'
      fullPath: '/operations/health'
      preLoaderRoute: typeof AppOperationsHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/deployments': {
      id: '/_app/operations/deployments'
      path: '/operations/deployments'
      fullPath: '/operations/deployments'
      preLoaderRoute: typeof AppOperationsDeploymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/projects': {
      id: '/_app/clients/projects'
      path: '/clients/projects'
      fullPath: '/clients/projects'
      preLoaderRoute: typeof AppClientsProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/deliverables': {
      id: '/_app/clients/deliverables'
      path: '/clients/deliverables'
      fullPath: '/clients/deliverables'
      preLoaderRoute: typeof AppClientsDeliverablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation/workflows': {
      id: '/_app/automation/workflows'
      path: '/automation/workflows'
      fullPath: '/automation/workflows'
      preLoaderRoute: typeof AppAutomationWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation/knowledge': {
      id: '/_app/automation/knowledge'
      path: '/automation/knowledge'
      fullPath: '/automation/knowledge'
      preLoaderRoute: typeof AppAutomationKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation/integrations': {
      id: '/_app/automation/integrations'
      path: '/automation/integrations'
      fullPath: '/automation/integrations'
      preLoaderRoute: typeof AppAutomationIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation/agents': {
      id: '/_app/automation/agents'
      path: '/automation/agents'
      fullPath: '/automation/agents'
      preLoaderRoute: typeof AppAutomationAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/usage': {
      id: '/_app/analytics/usage'
      path: '/analytics/usage'
      fullPath: '/analytics/usage'
      preLoaderRoute: typeof AppAnalyticsUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/revenue': {
      id: '/_app/analytics/revenue'
      path: '/analytics/revenue'
      fullPath: '/analytics/revenue'
      preLoaderRoute: typeof AppAnalyticsRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/performance': {
      id: '/_app/analytics/performance'
      path: '/analytics/performance'
      fullPath: '/analytics/performance'
      preLoaderRoute: typeof AppAnalyticsPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/team': {
      id: '/_app/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AppAdminTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/billing': {
      id: '/_app/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AppAdminBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/opportunities/$opportunityId': {
      id: '/_app/sales/opportunities/$opportunityId'
      path: '/$opportunityId'
      fullPath: '/sales/opportunities/$opportunityId'
      preLoaderRoute: typeof AppSalesOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof AppSalesOpportunitiesRoute
    }
    '/_app/sales/leads/$leadId': {
      id: '/_app/sales/leads/$leadId'
      path: '/$leadId'
      fullPath: '/sales/leads/$leadId'
      preLoaderRoute: typeof AppSalesLeadsLeadIdRouteImport
      parentRoute: typeof AppSalesLeadsRoute
    }
    '/_app/sales/clients/$salesClientId': {
      id: '/_app/sales/clients/$salesClientId'
      path: '/sales/clients/$salesClientId'
      fullPath: '/sales/clients/$salesClientId'
      preLoaderRoute: typeof AppSalesClientsSalesClientIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSalesLeadsRouteChildren {
  AppSalesLeadsLeadIdRoute: typeof AppSalesLeadsLeadIdRoute
}

const AppSalesLeadsRouteChildren: AppSalesLeadsRouteChildren = {
  AppSalesLeadsLeadIdRoute: AppSalesLeadsLeadIdRoute,
}

const AppSalesLeadsRouteWithChildren = AppSalesLeadsRoute._addFileChildren(
  AppSalesLeadsRouteChildren,
)

interface AppSalesOpportunitiesRouteChildren {
  AppSalesOpportunitiesOpportunityIdRoute: typeof AppSalesOpportunitiesOpportunityIdRoute
}

const AppSalesOpportunitiesRouteChildren: AppSalesOpportunitiesRouteChildren = {
  AppSalesOpportunitiesOpportunityIdRoute:
    AppSalesOpportunitiesOpportunityIdRoute,
}

const AppSalesOpportunitiesRouteWithChildren =
  AppSalesOpportunitiesRoute._addFileChildren(
    AppSalesOpportunitiesRouteChildren,
  )

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppTasksRoute: typeof AppTasksRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBillingRoute: typeof AppAdminBillingRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminTeamRoute: typeof AppAdminTeamRoute
  AppAnalyticsPerformanceRoute: typeof AppAnalyticsPerformanceRoute
  AppAnalyticsRevenueRoute: typeof AppAnalyticsRevenueRoute
  AppAnalyticsUsageRoute: typeof AppAnalyticsUsageRoute
  AppAutomationAgentsRoute: typeof AppAutomationAgentsRoute
  AppAutomationIntegrationsRoute: typeof AppAutomationIntegrationsRoute
  AppAutomationKnowledgeRoute: typeof AppAutomationKnowledgeRoute
  AppAutomationWorkflowsRoute: typeof AppAutomationWorkflowsRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsDeliverablesRoute: typeof AppClientsDeliverablesRoute
  AppClientsProjectsRoute: typeof AppClientsProjectsRoute
  AppOperationsDeploymentsRoute: typeof AppOperationsDeploymentsRoute
  AppOperationsHealthRoute: typeof AppOperationsHealthRoute
  AppOperationsTasksRoute: typeof AppOperationsTasksRoute
  AppOperationsTeamRoute: typeof AppOperationsTeamRoute
  AppProvisioningDomainsRoute: typeof AppProvisioningDomainsRoute
  AppProvisioningQueueRoute: typeof AppProvisioningQueueRoute
  AppProvisioningSecretsRoute: typeof AppProvisioningSecretsRoute
  AppProvisioningTemplatesRoute: typeof AppProvisioningTemplatesRoute
  AppSalesConversationsRoute: typeof AppSalesConversationsRoute
  AppSalesLeadsRoute: typeof AppSalesLeadsRouteWithChildren
  AppSalesOpportunitiesRoute: typeof AppSalesOpportunitiesRouteWithChildren
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppSalesClientsSalesClientIdRoute: typeof AppSalesClientsSalesClientIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppTasksRoute: AppTasksRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBillingRoute: AppAdminBillingRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminTeamRoute: AppAdminTeamRoute,
  AppAnalyticsPerformanceRoute: AppAnalyticsPerformanceRoute,
  AppAnalyticsRevenueRoute: AppAnalyticsRevenueRoute,
  AppAnalyticsUsageRoute: AppAnalyticsUsageRoute,
  AppAutomationAgentsRoute: AppAutomationAgentsRoute,
  AppAutomationIntegrationsRoute: AppAutomationIntegrationsRoute,
  AppAutomationKnowledgeRoute: AppAutomationKnowledgeRoute,
  AppAutomationWorkflowsRoute: AppAutomationWorkflowsRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsDeliverablesRoute: AppClientsDeliverablesRoute,
  AppClientsProjectsRoute: AppClientsProjectsRoute,
  AppOperationsDeploymentsRoute: AppOperationsDeploymentsRoute,
  AppOperationsHealthRoute: AppOperationsHealthRoute,
  AppOperationsTasksRoute: AppOperationsTasksRoute,
  AppOperationsTeamRoute: AppOperationsTeamRoute,
  AppProvisioningDomainsRoute: AppProvisioningDomainsRoute,
  AppProvisioningQueueRoute: AppProvisioningQueueRoute,
  AppProvisioningSecretsRoute: AppProvisioningSecretsRoute,
  AppProvisioningTemplatesRoute: AppProvisioningTemplatesRoute,
  AppSalesConversationsRoute: AppSalesConversationsRoute,
  AppSalesLeadsRoute: AppSalesLeadsRouteWithChildren,
  AppSalesOpportunitiesRoute: AppSalesOpportunitiesRouteWithChildren,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppSalesClientsSalesClientIdRoute: AppSalesClientsSalesClientIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
